name: cnnPy3
dependencies:
- appnope=0.1.0=py34_0
- backports_abc=0.4=py34_0
- cycler=0.10.0=py34_0
- decorator=4.0.9=py34_0
- freetype=2.5.5=0
- h5py=2.5.0=np110py34_4
- hdf5=1.8.15.1=2
- ipykernel=4.3.1=py34_0
- ipython=4.1.2=py34_0
- ipython-notebook=4.0.4=py34_0
- ipython_genutils=0.1.0=py34_0
- jbig=2.1=0
- jinja2=2.8=py34_0
- jpeg=8d=1
- jsonschema=2.4.0=py34_0
- jupyter_client=4.2.2=py34_0
- jupyter_core=4.1.0=py34_0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- markupsafe=0.23=py34_0
- matplotlib=1.5.1=np110py34_0
- mistune=0.7.2=py34_1
- mkl=11.3.1=0
- nbconvert=4.1.0=py34_0
- nbformat=4.0.1=py34_0
- networkx=1.11=py34_0
- notebook=4.1.0=py34_2
- numpy=1.10.4=py34_0
- openssl=1.0.2g=0
- path.py=8.1.2=py34_1
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pillow=3.1.1=py34_0
- pip=8.1.1=py34_0
- ptyprocess=0.5=py34_0
- pygments=2.1.1=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- python=3.4.4=0
- python-dateutil=2.5.1=py34_0
- python.app=1.2=py34_4
- pytz=2016.2=py34_0
- pyzmq=15.2.0=py34_0
- qt=4.8.7=1
- readline=6.2=2
- scikit-image=0.12.3=np110py34_0
- scipy=0.17.0=np110py34_0
- setuptools=20.3=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- sqlite=3.9.2=0
- terminado=0.5=py34_1
- tk=8.5.18=0
- tornado=4.3=py34_0
- traitlets=4.2.1=py34_0
- wheel=0.29.0=py34_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - keras==0.3.2
  - pyyaml==3.11
  - theano==0.8.0

